version: '3'

services:
  postgres:
    image: 'postgres:17'
    container_name: 'nutrition-db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=qwerty1234'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=nutrition'
  app:
    build: ./
    container_name: 'nutrition-app'
    ports:
      - "8080:8080"